import { type NextRequest, NextResponse } from "next/server"
import { cookies } from "next/headers"
import clientPromise from "@/lib/mongodb"
import { ObjectId } from "mongodb"

export async function POST(request: NextRequest) {
  try {
    // 1. Get the current user from the session cookie
    const cookieStore = await cookies()
    const sessionCookie = cookieStore.get("session")

    if (!sessionCookie) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    const session = JSON.parse(sessionCookie.value)
    const user = session.user

    if (!user || !user.id) {
      return NextResponse.json({ error: "Invalid session" }, { status: 401 })
    }

    // 2. Parse the request (Game Score/Details)
    const { game, code } = await request.json()

    // 3. Connect to Database
    const client = await clientPromise
    if (!client) throw new Error("Database connection failed")
    const db = client.db("intellicafe")

    // --- LOGIC: LIMIT 5 PER DAY ---
    
    // Calculate the start of the current day (00:00:00)
    const startOfDay = new Date()
    startOfDay.setHours(0, 0, 0, 0)

    // Count how many vouchers this user created today
    const vouchersToday = await db.collection("vouchers").countDocuments({
      userId: user.id, // Ensure we check only this user
      createdAt: { $gte: startOfDay } // Created "Greater Than or Equal to" today 00:00
    })

    // If they have reached the limit, stop them
    if (vouchersToday >= 5) {
      return NextResponse.json(
        { error: "Daily limit reached. You can only earn 5 vouchers per day." },
        { status: 429 } // 429 = Too Many Requests
      )
    }

    // -----------------------------

    // 4. Create the new Voucher
    const newVoucher = {
      userId: user.id,
      userName: user.name, // Storing name helps the admin view
      game: game || "General",
      code: code, // The code generated by the game (or generate one here if needed)
      status: "active", // active vs redeemed
      createdAt: new Date(),
    }

    await db.collection("vouchers").insertOne(newVoucher)

    return NextResponse.json({ success: true, voucher: newVoucher })

  } catch (error) {
    console.error("Voucher API Error:", error)
    return NextResponse.json({ error: "Internal Server Error" }, { status: 500 })
  }
}

// GET method to fetch vouchers (for Admin or User)
export async function GET(request: NextRequest) {
    try {
        const client = await clientPromise
        if (!client) throw new Error("Database connection failed")
        const db = client.db("intellicafe")

        // Fetch all vouchers (sorted by newest first)
        const vouchers = await db.collection("vouchers")
            .find({})
            .sort({ createdAt: -1 })
            .toArray()

        return NextResponse.json(vouchers)
    } catch (error) {
        return NextResponse.json({ error: "Failed to fetch vouchers" }, { status: 500 })
    }
}

// PUT method to Redeem a voucher (Admin Only)
export async function PUT(request: NextRequest) {
    try {
        const { id } = await request.json()
        
        const client = await clientPromise
        if (!client) throw new Error("Database connection failed")
        const db = client.db("intellicafe")

        await db.collection("vouchers").updateOne(
            { _id: new ObjectId(id) },
            { 
                $set: { 
                    status: "redeemed",
                    redeemedAt: new Date()
                } 
            }
        )

        return NextResponse.json({ success: true })
    } catch (error) {
        return NextResponse.json({ error: "Failed to redeem" }, { status: 500 })
    }
}